In [1]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

# Review

In [4]:
cones = Table.read_table('cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

### Discussion Q1

In [ ]:
# Find percentage of rows that match the condition color pink

In [18]:
pink_cones = cones.where('Color', 'pink')
pink_cones

Flavor     | Color | Price
strawberry | pink  | 3.55
strawberry | pink  | 5.25
bubblegum  | pink  | 4.75

In [7]:
pink_cones.num_rows / cones.num_rows * 100

50.0

### Discussion Question 2

What does the following evaluate to

```
x = 5
y = 7

max(x, y)
min(x-y, x+y, x*y, x/y)
round(x/y)
x * 2.5
y + '5'

```

In [8]:
x = 5
y = 7

In [9]:
# Case 1
max(x, y)

7

In [10]:
# Case 2
min(x-y, x+y, x*y, x/y)

-2

In [11]:
# Case 3
round(x/y)

1

In [16]:
# Case 4
x * 2.5

12.5

In [21]:
# Case 5
y + '5'

TypeError: unsupported operand type(s) for +: 'int' and 'str'

## Numbers ##

In [ ]:
30

In [22]:
3 * 30 # int

90

In [23]:
10 / 3 # float

3.3333333333333335

In [34]:
3 / 3

1.0

In [24]:
10 ** 3 # 10 * 10 * 10 

1000

In [26]:
10 ** 0.5 # float

3.1622776601683795

In [27]:
12345678 ** 890

ValueError: Exceeds the limit (4300 digits) for integer string conversion; use sys.set_int_max_str_digits() to increase the limit

In [ ]:
75892745.215489247589274985712

In [ ]:
75892745.215489247589274985712 - 75892745.21548925

In [29]:
10 / 5

2.0

In [28]:
int(10 / 5)

2

In [35]:
16 / 30

0.5333333333333333

In [36]:
round(16 / 30), int(16 / 30)

(1, 0)

In [ ]:
round(6/10), int(6/10)

In [37]:
float(3)

3.0

In [39]:
1e-6

1e-06

In [ ]:
1e-56

## Strings ##

In [40]:
'Flavor'

'Flavor'

In [41]:
"Flavor"

'Flavor'

In [ ]:
'"This is a quote from Jeremy"'

In [ ]:
Flavor

In [45]:
'Don't do this'

SyntaxError: unterminated string literal (detected at line 1) (2239797020.py, line 1)

In [46]:
'straw' + 'berry'

'strawberry'

In [47]:
'Chris' + ' ' + 'is' + ' ' + 'cool'

'Chris is cool'

In [48]:
name = 'Chris'
name + ' is not all that cool'

'Chris is not all that cool'

In [49]:
'ha' * 1000

'hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahah

In [ ]:
'HA' * 1.5

In [ ]:
'ha' + 10

In [50]:
5 + int('5')

10

In [ ]:
'yelp review:' + str(10)

In [ ]:
int('3.0')

In [ ]:
int(float('3.0'))

## Types ##

In [51]:
type(10)

int

In [52]:
type(10.5)

float

In [53]:
type('apple juice')

str

In [55]:
Kanu = 'kevin'
Kevin = 'kevin'
Ciara = 'ciara'

In [58]:
Kanu == Kevin

True

In [59]:
Ciara == Kevin

False

In [60]:
type(Ciara == Kevin)

bool

In [62]:
abs(-5)

5

In [66]:
type(abs)

builtin_function_or_method

## Arrays ##

In [89]:
my_array = make_array(1, 2, 3)

In [80]:
my_array

array([1, 2, 3])

In [70]:
type(my_array)

numpy.ndarray

In [71]:
len(my_array)

3

In [87]:
my_array + 2

array([5, 6, 7])

In [73]:
my_array * 2

array([2, 4, 6])

In [74]:
my_array = my_array ** 2

In [90]:
my_array

array([1, 2, 3])

In [91]:
my_array_2 = make_array(-1, -2, -1)

In [92]:
my_array_2 + my_array

array([0, 0, 2])

In [93]:
my_array_3 = make_array(1,2,3,4)

In [94]:
my_array_3

array([1, 2, 3, 4])

In [95]:
my_array + my_array_3

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [96]:
names_array = make_array('Andrew', "Conan", 'Jonathan')
names_array

array(['Andrew', 'Conan', 'Jonathan'],
      dtype='<U8')

In [97]:
names_array.item(0)

'Andrew'

In [98]:
names_array.item(1)

'Conan'

In [ ]:
names_array.item(3)

## Columns of Tables are Arrays ##

In [101]:
nba = Table.read_table('nba_salaries.csv').relabeled(4, 'SALARY')
warriors = nba.where('team', 'Golden State Warriors')

In [102]:
warriors

rank | name              | position | team                  | SALARY  | season
41   | Donyell Marshall  | PF       | Golden State Warriors | 5250000 | 2000
47   | Erick Dampier     | C        | Golden State Warriors | 4988000 | 2000
58   | Mookie Blaylock   | G        | Golden State Warriors | 4200000 | 2000
59   | Chris Mills       | SF       | Golden State Warriors | 4200000 | 2000
64   | Jason Caffey      | F        | Golden State Warriors | 3937000 | 2000
89   | Vonteego Cummings | PG       | Golden State Warriors | 2600000 | 2000
92   | Antawn Jamison    | PF       | Golden State Warriors | 2503000 | 2000
73   | Erick Dampier     | C        | Golden State Warriors | 5611000 | 2001
91   | Mookie Blaylock   | G        | Golden State Warriors | 4800000 | 2001
92   | Chris Mills       | SF       | Golden State Warriors | 4800000 | 2001
... (301 rows omitted)

In [103]:
type(warriors.select('SALARY'))
# Returns a column in a table format

datascience.tables.Table

In [104]:
SALARY = warriors.column('SALARY')

In [106]:
type(SALARY)

numpy.ndarray

In [105]:
#np.average(warriors.select('SALARY'))
# can't call numpy function on tables

TypeError: the resolved dtypes are not compatible with add.reduce. Resolved (dtype('<U6'), dtype('<U6'), dtype('<U12'))

In [108]:
warriors.column('SALARY')

array([ 5250000,  4988000,  4200000,  4200000,  3937000,  2600000,
        2503000,  5611000,  4800000,  4800000,  4386000,  3578000,
        3390000,  2678000,  1842000,   757000,   316000,   316000,
         241000,    32000,  6235000,  5400000,  5400000,  4913000,
        4441000,  4400000,  3388000,  3000000,  2343000,  2021000,
        1310000,   333000,   333000,  6858000,  6000000,  5540000,
        4935000,  4469000,  4400000,  1409000,   700000,   512000,
       10912000,  7482000,  5445000,  4400000,  1667000,  1507000,
        3000000,  2481000,  2390000,  2232000, 13700000,  8888888,
        7365079,  7312500,  5393300,  4506261,  1988160,  1910520,
        1857360,  1760000,  1404360,   448762,   423762, 15070000,
        9999999,  8125000,  2535260,  2157097,  2061720,  1986960,
         798112,   744551,   664209,   259770, 16440000,  8425625,
        6630000,  4000000,  3470771,  3000000,  2636696,  2323080,
        2216400,  1800000,  1345800,   770610,   770610,   687

In [107]:
np.average(warriors.column('SALARY'))

4315935.9228295824

In [112]:
warriors.where('name', 'Chris Mills')

rank | name        | position | team                  | SALARY  | season
59   | Chris Mills | SF       | Golden State Warriors | 4200000 | 2000
92   | Chris Mills | SF       | Golden State Warriors | 4800000 | 2001
79   | Chris Mills | SF       | Golden State Warriors | 5400000 | 2002
72   | Chris Mills | SF       | Golden State Warriors | 6000000 | 2003

In [109]:
np.average(warriors.where('name', 'Chris Mills').column('SALARY'))

5100000.0

In [115]:
warriors.where('name', 'Chris Mills').column('SALARY').item(0)

4200000

## Ranges ##

In [ ]:
np.arange(10) # make_array(0,1,2,3,4,5,6,7,8,9)
# np.arange(END)

In [ ]:
np.arange(1, 10)
# np.arange(START, END)

In [ ]:
np.arange(1, 10, 2)
# np.arange(START, END, STEP)

In [ ]:
np.arange(1, 11)

In [ ]:
np.arange(1, 10.1)

## take Function  ##

In [23]:
nba = Table.read_table('nba_salaries.csv')
nba = nba.sort('salary', descending = True)
nba

rank | name              | position | team                  | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets       | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards    | 38199000 | 2020
5    | Kevin Durant      | SF       | Brooklyn Nets         | 38199000 | 2020
6    | James Harden      | SG       | Houston Rockets       | 38199000 | 2020
1    | Stephen Curry     | PG       | Golden State Warriors | 37457154 | 2018
1    | Stephen Curry     | PG       | Golden State Warriors | 37457154 | 2019
7    | LeBron James      | SF       | Los Angeles Lakers    | 37436858 | 2020
2    | Chris Paul        | PG       | Houston Rockets       | 35654150 | 2019
... (9446 rows omitted)

In [24]:
top_ten_salary = nba.take(np.arange(10))
top_ten_salary

rank | name              | position | team                  | salary   | season
1    | Stephen Curry     | PG       | Golden State Warriors | 40231758 | 2020
2    | Chris Paul        | PG       | Oklahoma City Thunder | 38506482 | 2020
3    | Russell Westbrook | PG       | Houston Rockets       | 38506482 | 2020
4    | John Wall         | PG       | Washington Wizards    | 38199000 | 2020
5    | Kevin Durant      | SF       | Brooklyn Nets         | 38199000 | 2020
6    | James Harden      | SG       | Houston Rockets       | 38199000 | 2020
1    | Stephen Curry     | PG       | Golden State Warriors | 37457154 | 2018
1    | Stephen Curry     | PG       | Golden State Warriors | 37457154 | 2019
7    | LeBron James      | SF       | Los Angeles Lakers    | 37436858 | 2020
2    | Chris Paul        | PG       | Houston Rockets       | 35654150 | 2019

## Reading a Table from a File  ##

In [2]:
du_bois = Table.read_table('du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

## Discussion Question

Use the table functions we learned this week to find the income bracket (“class”) that spent the highest percentage of their income on rent.

In [ ]:
du_bois.sort('RENT', descending = True).column('CLASS').item(0)

# Lecture 4b: Census

## Census ##

In [5]:
full = Table.read_table('nc-est2019-agesex-res.csv')
full

SEX  | AGE  | CENSUS2010POP | ESTIMATESBASE2010 | POPESTIMATE2010 | POPESTIMATE2011 | POPESTIMATE2012 | POPESTIMATE2013 | POPESTIMATE2014 | POPESTIMATE2015 | POPESTIMATE2016 | POPESTIMATE2017 | POPESTIMATE2018 | POPESTIMATE2019
0    | 0    | 3944153       | 3944160           | 3951430         | 3963092         | 3926570         | 3931258         | 3954787         | 3983981         | 3954773         | 3893990         | 3815343         | 3783052
0    | 1    | 3978070       | 3978090           | 3957730         | 3966225         | 3977549         | 3942698         | 3948891         | 3973133         | 4002903         | 3972711         | 3908830         | 3829599
0    | 2    | 4096929       | 4096939           | 4090621         | 3970654         | 3978925         | 3991740         | 3958711         | 3966321         | 3991349         | 4020045         | 3987032         | 3922044
0    | 3    | 4119040       | 4119051           | 4111688         | 4101644         | 3981531         | 3991017         | 4005928         | 3974351         | 3982984         | 4006946         | 4033038         | 3998665
0    | 4    | 4063170       | 4063186           | 4077346         | 4121488         | 4111490         | 3992502         | 4004032         | 4020292         | 3989750         | 3997280         | 4018719         | 4043323
0    | 5    | 4056858       | 4056872           | 4064521         | 4087054         | 4131049         | 4121876         | 4004576         | 4017589         | 4035033         | 4003452         | 4008443         | 4028281
0    | 6    | 4066381       | 4066412           | 4072904         | 4074531         | 4096631         | 4141126         | 4133372         | 4017388         | 4031568         | 4048018         | 4014057         | 4017227
0    | 7    | 4030579       | 4030594           | 4042990         | 4082821         | 4084175         | 4106756         | 4152666         | 4145872         | 4030888         | 4044139         | 4058370         | 4022319
0    | 8    | 4046486       | 4046497           | 4025501         | 4052773         | 4092559         | 4094513         | 4118349         | 4165033         | 4158848         | 4042924         | 4054236         | 4066194
0    | 9    | 4148353       | 4148369           | 4125312         | 4035319         | 4062726         | 4103052         | 4106068         | 4130887         | 4177895         | 4170813         | 4053179         | 4061874
... (296 rows omitted)

In [9]:
partial = full.select('SEX', 'AGE', 'POPESTIMATE2014', 'POPESTIMATE2019')
partial.show(5)

In [10]:
us_pop = partial.relabeled(2, '2014').relabeled(3, '2019')
us_pop.show(5)

In [11]:
us_pop.where('AGE', are.above_or_equal_to(100))

SEX  | AGE  | 2014      | 2019
0    | 100  | 70685     | 100322
0    | 999  | 318301008 | 328239523
1    | 100  | 13577     | 23472
1    | 999  | 156654424 | 161657324
2    | 100  | 57108     | 76850
2    | 999  | 161646584 | 166582199

In [6]:
us_pop.where('AGE', >= 100)

SyntaxError: invalid syntax (2376882552.py, line 1)

**Discussion Question:** Construct a table containing the top three most populous ages (male and female combined) in the year 2019.

In [21]:
ages2020 = full.select('SEX', 'AGE', 'POPESTIMATE2019')
#ages2020 = ages2020.where('SEX', are.equal_to(0))
#ages2020 = ages2020.drop('SEX')
#ages2020 = ages2020.sort('POPESTIMATE2019', descending = True)
#ages2020 = ages2020.where('AGE', are.not_equal_to(999))
#ages2020 = ages2020.take(np.arange(3))
#ages2020

AGE  | POPESTIMATE2019
28   | 4818725
29   | 4806144
27   | 4733869

## 2019 Sex Ratios ##

In [ ]:
us_pop_2019 = us_pop.drop('2014')
us_pop_2019.show(3)

In [ ]:
all_ages = us_pop_2019.where('AGE', are.equal_to(999))
all_ages

In [ ]:
infants = us_pop_2019.where('AGE', are.equal_to(0))
infants

In [ ]:
females_all_rows = us_pop_2019.where('SEX', are.equal_to(2))
females = females_all_rows.where('AGE', are.not_equal_to(999))
females.show(3)

In [ ]:
males_all_rows = us_pop_2019.where('SEX', are.equal_to(1))
males = males_all_rows.where('AGE', are.not_equal_to(999))
males.show(3)

In [ ]:
f_to_m_ratios = females.column(2) / males.column(2)

ratios = Table().with_columns(
    'Age', females.column('AGE'),
    'F:M Ratio', f_to_m_ratios
)

ratios

In [ ]:
ratios.sort('Age', descending=True)

## Line Plot ##

In [ ]:
ratios.plot('Age', 'F:M Ratio')

## Optional: Adding a Title to a Plot ##

In [ ]:
ratios.plot('Age', 'F:M Ratio')
plots.title('2019 US Population');

## Optional: set_format and PercentFormatter ##

In [ ]:
infants

In [ ]:
total_infants_2019 = infants.column('2019').item(0)
total_infants_2019

In [ ]:
infants = infants.with_column(
    'Proportion', infants.column('2019')/total_infants_2019
)
infants

In [ ]:
# A more easily readable display
# Displays proportions as percents
infants.set_format('Proportion', PercentFormatter)

In [ ]:
# Once the format is set, it remains.
infants